const tableData = [
    {
        key: "1",
        channel: "Custom",
        order: "STP2332ON",
        date: "09-12-2021",
        product: "Veg Chopper",
        payment: "650",
        method: "COD",
        customer: "Yash Raj",
        carrier: "Delhivery",
        awb: "6786544567",
        tags: ["nice", "developer"],
        status: "Delivered",
    },
    {
        key: "2",
        channel: "Custom",
        order: "WOM43287",
        date: "24-12-2021",
        product: "Mobile Charger",
        payment: "650",
        method: "COD",
        customer: "Yash Raj",
        carrier: "Delhivery",
        awb: "6786544567",
        tags: ["cool", "teacher"],
        status: "Delivered",
    },
    {
        key: "3",
        channel: "Custom",
        order: "WER48357",
        date: "25-02-2021",
        product: "Peanut Butter",
        payment: "300",
        method: "COD",
        customer: "Ramson",
        carrier: "Delhivery",
        awb: "876567876",
        tags: ["loser"],
        status: "Delivered",
    },
    {
        key: "4",
        channel: "Custom",
        order: "STP2332ON",
        date: "09-12-2021",
        product: "Matrex",
        payment: "650",
        method: "COD",
        customer: "Yash Raj",
        carrier: "Delhivery",
        awb: "6786544567",
        tags: ["nice", "developer"],
        status: "Delivered",
    },
    {
        key: "5",
        channel: "Custom",
        order: "WER48357",
        date: "25-02-2021",
        product: "Peanut Butter",
        payment: "300",
        method: "COD",
        customer: "Ramson",
        carrier: "Ecart",
        awb: "876567876",
        tags: ["cool", "teacher"],
        status: "Delivered",
    },
    {
        key: "6",
        channel: "Custom",
        order: "WER48357",
        date: "09-12-2021",
        product: "Pillow",
        payment: "650",
        method: "Online",
        customer: "John Brown",
        carrier: "Ecart",
        awb: "6786544567",
        tags: ["loser"],
        status: "Delivered",
    },
    {
        key: "7",
        channel: "Custom",
        order: "WER48357",
        date: "09-12-2021",
        product: "Pillow",
        payment: "650",
        method: "Online",
        customer: "Yash Raj",
        carrier: "ECOM Express",
        awb: "6786544567",
        tags: ["hello", "jug"],
        status: "Delivered",
    },
    {
        key: "8",
        channel: "Custom",
        order: "WER483532",
        date: "09-12-2021",
        product: "Pillow",
        payment: "650",
        method: "Online",
        customer: "Lokesh",
        carrier: "Ecart",
        awb: "6786544567",
        tags: ["hello", "jug"],
        status: "Delivered",
    },
    {
        key: "9",
        channel: "Custom",
        order: "WER48357",
        date: "09-12-2021",
        product: "Chopper",
        payment: "650",
        method: "COD",
        customer: "Shivam singh",
        carrier: "Ecart",
        awb: "6786544567",
        tags: ["loser"],
        status: "Delivered",
    },
    {
        key: "10",
        channel: "Custom",
        order: "WER48357",
        date: "09-12-2021",
        product: "Water bottle",
        payment: "900",
        method: "COD",
        customer: "Shivam",
        carrier: "Delhivery",
        awb: "990987896",
        tags: ["hello", "jug"],
        status: "In Transit",
    },
    {
        key: "11",
        channel: "Custom",
        order: "WER48357",
        date: "09-12-2021",
        product: "Pillow",
        payment: "650",
        method: "Online",
        customer: "Yash Raj",
        carrier: "ECOM Express",
        awb: "6786544567",
        tags: ["hello", "jug"],
        status: "Delivered",
    },
    {
        key: "12",
        channel: "Custom",
        order: "WER483532",
        date: "09-12-2021",
        product: "Pillow",
        payment: "650",
        method: "Online",
        customer: "Lokesh",
        carrier: "Ecart",
        awb: "6786544567",
        tags: ["hello", "jug"],
        status: "Delivered",
    },
    {
        key: "13",
        channel: "Custom",
        order: "WER48357",
        date: "09-12-2021",
        product: "Chopper",
        payment: "650",
        method: "COD",
        customer: "Shivam singh",
        carrier: "Ecart",
        awb: "6786544567",
        tags: ["loser"],
        status: "Delivered",
    },
    {
        key: "14",
        channel: "Custom",
        order: "WER48357",
        date: "09-12-2021",
        product: "Water bottle",
        payment: "900",
        method: "COD",
        customer: "Shivam",
        carrier: "Delhivery",
        awb: "990987896",
        tags: ["hello", "jug"],
        status: "In Transit",
    },
    {
        key: "15",
        channel: "Custom",
        order: "WOM43287",
        date: "24-12-2021",
        product: "Mobile Charger",
        payment: "650",
        method: "COD",
        customer: "Yash Raj",
        carrier: "Delhivery",
        awb: "6786544567",
        tags: ["cool", "teacher"],
        status: "Delivered",
    },
    {
        key: "16",
        channel: "Custom",
        order: "WER48357",
        date: "25-02-2021",
        product: "Peanut Butter",
        payment: "300",
        method: "COD",
        customer: "Ramson",
        carrier: "Delhivery",
        awb: "876567876",
        tags: ["loser"],
        status: "Delivered",
    },
];

export default tableData;